### PR TITLE
Resize icons

### PR DESCRIPTION
**Pull request by danstewart**
Workaround for #644 

Issue as that if the icon does not exist in the icon pack we don't attempt to resize the image:
https://github.com/fedy/fedy/blob/master/app.js#L504-L520

This PR just resizes them for now but will look into a better solution at some point.

### CODE REVIEW

**Comment by sudoforge** [comment]
I'll be around and working through the backlog today.

Could we get `refers 644` or `closes 644` in the commit body?

**Comment by danstewart** [comment]
@sudoforge Commit message updated. 

Thought about it a little more and I'm not sure if it's temporary or not.
The issue is we don't automatically scale icons that we bundle with fedy, but I suppose we should be bundling correctly sized icons in the first place (48x48 in size).

I think we can scale them automatically when displaying (though we might need to add a dependency) but we may as well just scale them when we add them in the first place.

**Comment by danstewart** [comment]
Just reverted the change to `.gitattributes` too.
I tracked all 4 of the icons with `git lfs` unnecessarily.

**Comment by danstewart** [comment]
Nevermind, that's made a mess of it since it was tracked with `git lfs` and now it's not...
I'll redo this.

**Pull request closed without merging**
